version: "3"
services:
  mongodbsetup:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
    volumes:
      - testvolume1:/data/db

  mongoexpresss:
    image: mongo-express
    container_name: mongoexpress
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwerty
      ME_CONFIG_MONGODB_URL: mongodb://admin:qwerty@mongo:27017/?authSource=admin

  app:
    image: rakeshdevarakonda/test1
    container_name: myapp
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://admin:qwerty@mongo:27017/dockertest?authSource=admin
    depends_on:
      - mongodbsetup

volumes:
  testvolume1: {}
